"""edit busy_times model

Revision ID: 82b66ec677ab
Revises: e1139ff9dc8b
Create Date: 2024-07-28 23:34:50.069645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID


# revision identifiers, used by Alembic.
revision: str = '82b66ec677ab'
down_revision: Union[str, None] = 'e1139ff9dc8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('busy_times', sa.Column('user_id', GUID(), nullable=False))
    op.add_column('busy_times', sa.Column('was_paid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('busy_times', 'was_paid')
    op.drop_column('busy_times', 'user_id')
    # ### end Alembic commands ###
