"""Initial models with tg bot

Revision ID: 8b1edeaa5653
Revises: 
Create Date: 2024-08-02 22:40:56.278630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID

# revision identifiers, used by Alembic.
revision: str = '8b1edeaa5653'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('style', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('air_conditioner', sa.Boolean(), nullable=False),
    sa.Column('place', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('bath', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('reservations',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.Date(), server_default='2024-08-02', nullable=False),
    sa.Column('end', sa.Date(), server_default='2024-08-03', nullable=False),
    sa.Column('full_price', sa.Integer(), nullable=False),
    sa.Column('was_paid', sa.String(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('user_id', GUID(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('houses')
    # ### end Alembic commands ###
