"""edit busy_times model

Revision ID: b1747a755fcb
Revises: ce5cd0775e00
Create Date: 2024-07-26 21:46:37.639025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1747a755fcb'
down_revision: Union[str, None] = 'ce5cd0775e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('busy_times', sa.Column('email', sa.String(length=320), nullable=False))
    op.add_column('busy_times', sa.Column('number', sa.String(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('busy_times', 'number')
    op.drop_column('busy_times', 'email')
    # ### end Alembic commands ###
