"""remove aouth2

Revision ID: ce5cd0775e00
Revises: 8ff44afbe364
Create Date: 2024-07-26 14:55:13.854821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5cd0775e00'
down_revision: Union[str, None] = '8ff44afbe364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_oauth_account_account_id', table_name='oauth_account')
    op.drop_index('ix_oauth_account_oauth_name', table_name='oauth_account')
    op.drop_table('oauth_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_account',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('oauth_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('expires_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('account_email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='oauth_account_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='oauth_account_pkey')
    )
    op.create_index('ix_oauth_account_oauth_name', 'oauth_account', ['oauth_name'], unique=False)
    op.create_index('ix_oauth_account_account_id', 'oauth_account', ['account_id'], unique=False)
    # ### end Alembic commands ###
