"""edit busy_times model

Revision ID: e1139ff9dc8b
Revises: b1747a755fcb
Create Date: 2024-07-26 22:30:56.122965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1139ff9dc8b'
down_revision: Union[str, None] = 'b1747a755fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('busy_times', 'start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('busy_times', 'end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_constraint('busy_times_house_id_fkey', 'busy_times', type_='foreignkey')
    op.create_foreign_key(None, 'busy_times', 'houses', ['house_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'busy_times', type_='foreignkey')
    op.create_foreign_key('busy_times_house_id_fkey', 'busy_times', 'houses', ['house_id'], ['id'], ondelete='CASCADE')
    op.alter_column('busy_times', 'end',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('busy_times', 'start',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
