worker_processes auto;

events {
    worker_connections 2048;
    multi_accept on;
};

http {
    keepalive_timeout 45;
    reset_timedout_connection on;
    client_body_timeout 35;
    client_header_timeout 12;
    send_timeout 30;

    client_body_buffer_size 10k;
    client_header_buffer_size 1k;
    client_max_body_size 8m;
    large_client_header_buffers 4 4k;

    gzip on;
    gzip_min_length 500;
    gzip_vary on;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/javascript application/javascript application/x-javascript text/xml application/xml+rss application/json;
    gzip_disable "msie6";
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    
    sendfile      on;
    aio           on;
    tcp_nopush    on;

    open_file_cache max=100000 inactive=20s;
    open_file_cache_valid 45s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;

    server {
        listen 80;
        server_name http://127.0.0.1;

        client_max_body_size 32m;

        location ^~ /.well-known/acme-challenge {
            default_type text/plain;
            root /var/www/letsencrypt;
        }
        
        location ~* \.(jpg|jpeg|png|gif|ico|svg)$ {
            expires 30d;
            add_header Cache-Control "public, max-age=2592000";
        }

        location ~* \.(css|js) {
            expires 365d;
        }

        location / {
            proxy_pass http://app:8000;
            return 301 https://$host$request_uri;        
        }
    }
}